/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface AgcWheatHarvestLossInputs {
    'socket': string;
  }
  interface AgcWheatHarvestLossInputsAttributes extends StencilHTMLAttributes {
    'socket'?: string;
  }

  interface AgcWheatHarvestLossProgress {
    'socket': string;
  }
  interface AgcWheatHarvestLossProgressAttributes extends StencilHTMLAttributes {
    'socket'?: string;
  }

  interface AgcWheatHarvestLossResultsPlaceholder {}
  interface AgcWheatHarvestLossResultsPlaceholderAttributes extends StencilHTMLAttributes {}

  interface AgcWheatHarvestLossResults {
    'socket': string;
  }
  interface AgcWheatHarvestLossResultsAttributes extends StencilHTMLAttributes {
    'socket'?: string;
  }

  interface AgcWheatHarvestLoss {
    'mode': 'full' | 'step';
    'socket': string;
    'tract': string;
    'units': any;
  }
  interface AgcWheatHarvestLossAttributes extends StencilHTMLAttributes {
    'mode'?: 'full' | 'step';
    'onAgcCalculated'?: (event: CustomEvent) => void;
    'onAgcStepChanged'?: (event: CustomEvent) => void;
    'socket'?: string;
    'tract'?: string;
    'units'?: any;
  }
}

declare global {
  interface StencilElementInterfaces {
    'AgcWheatHarvestLossInputs': Components.AgcWheatHarvestLossInputs;
    'AgcWheatHarvestLossProgress': Components.AgcWheatHarvestLossProgress;
    'AgcWheatHarvestLossResultsPlaceholder': Components.AgcWheatHarvestLossResultsPlaceholder;
    'AgcWheatHarvestLossResults': Components.AgcWheatHarvestLossResults;
    'AgcWheatHarvestLoss': Components.AgcWheatHarvestLoss;
  }

  interface StencilIntrinsicElements {
    'agc-wheat-harvest-loss-inputs': Components.AgcWheatHarvestLossInputsAttributes;
    'agc-wheat-harvest-loss-progress': Components.AgcWheatHarvestLossProgressAttributes;
    'agc-wheat-harvest-loss-results-placeholder': Components.AgcWheatHarvestLossResultsPlaceholderAttributes;
    'agc-wheat-harvest-loss-results': Components.AgcWheatHarvestLossResultsAttributes;
    'agc-wheat-harvest-loss': Components.AgcWheatHarvestLossAttributes;
  }


  interface HTMLAgcWheatHarvestLossInputsElement extends Components.AgcWheatHarvestLossInputs, HTMLStencilElement {}
  var HTMLAgcWheatHarvestLossInputsElement: {
    prototype: HTMLAgcWheatHarvestLossInputsElement;
    new (): HTMLAgcWheatHarvestLossInputsElement;
  };

  interface HTMLAgcWheatHarvestLossProgressElement extends Components.AgcWheatHarvestLossProgress, HTMLStencilElement {}
  var HTMLAgcWheatHarvestLossProgressElement: {
    prototype: HTMLAgcWheatHarvestLossProgressElement;
    new (): HTMLAgcWheatHarvestLossProgressElement;
  };

  interface HTMLAgcWheatHarvestLossResultsPlaceholderElement extends Components.AgcWheatHarvestLossResultsPlaceholder, HTMLStencilElement {}
  var HTMLAgcWheatHarvestLossResultsPlaceholderElement: {
    prototype: HTMLAgcWheatHarvestLossResultsPlaceholderElement;
    new (): HTMLAgcWheatHarvestLossResultsPlaceholderElement;
  };

  interface HTMLAgcWheatHarvestLossResultsElement extends Components.AgcWheatHarvestLossResults, HTMLStencilElement {}
  var HTMLAgcWheatHarvestLossResultsElement: {
    prototype: HTMLAgcWheatHarvestLossResultsElement;
    new (): HTMLAgcWheatHarvestLossResultsElement;
  };

  interface HTMLAgcWheatHarvestLossElement extends Components.AgcWheatHarvestLoss, HTMLStencilElement {}
  var HTMLAgcWheatHarvestLossElement: {
    prototype: HTMLAgcWheatHarvestLossElement;
    new (): HTMLAgcWheatHarvestLossElement;
  };

  interface HTMLElementTagNameMap {
    'agc-wheat-harvest-loss-inputs': HTMLAgcWheatHarvestLossInputsElement
    'agc-wheat-harvest-loss-progress': HTMLAgcWheatHarvestLossProgressElement
    'agc-wheat-harvest-loss-results-placeholder': HTMLAgcWheatHarvestLossResultsPlaceholderElement
    'agc-wheat-harvest-loss-results': HTMLAgcWheatHarvestLossResultsElement
    'agc-wheat-harvest-loss': HTMLAgcWheatHarvestLossElement
  }

  interface ElementTagNameMap {
    'agc-wheat-harvest-loss-inputs': HTMLAgcWheatHarvestLossInputsElement;
    'agc-wheat-harvest-loss-progress': HTMLAgcWheatHarvestLossProgressElement;
    'agc-wheat-harvest-loss-results-placeholder': HTMLAgcWheatHarvestLossResultsPlaceholderElement;
    'agc-wheat-harvest-loss-results': HTMLAgcWheatHarvestLossResultsElement;
    'agc-wheat-harvest-loss': HTMLAgcWheatHarvestLossElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
